# smart_food_bot/src/domain/repositories.py
from __future__ import annotations
from typing import Protocol, Iterable, List
from .entities import Recipe, Product

class RecipeReadRepo(Protocol):
    def all(self) -> List[Recipe]: ...
    def by_id(self, recipe_id: str) -> Recipe | None: ...

class ProductReadRepo(Protocol):
    def all(self) -> List[Product]: ...
    def find_by_name(self, name: str, top_k: int = 5) -> List[Product]: ...
